backend:
  name: git-gateway
  branch: main  # Replace with your default branch name

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
